
patientAdaptor:
  url: http://localhost:8081/billing/{patientId}

appointmentAdaptor:
  url: http://localhost:8082/appointment/{patientId}

recordsAdaptor:
  url: http://localhost:8083/record/{patientId}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patient
    username: root
    password: hello123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true