application:
    name: appointment-management

server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heathcareappointment
    username: root
    password: hello123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
