server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/billing
    username: root
    password: hello123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
